repos:
  - repo: local
    hooks:
      - id: linting
        name: Make Lint
        entry: make lint
        language: system
        types: [python]  # Specify which file types to check
        # Optionally, use 'files' to specify patterns
        # files: '.*\.py$'
