name: Release Drafter

on:
  push:
    tags:
      - '*'  # Run this workflow on any tag push
permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'dev')"  # Exclude tags containing "dev"
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
         config-name: release-drafter-template.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
