name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: pip install hatch

    - name: Run MyPy Check
      run :  hatch run types:check -py ${{ matrix.python-version }}


    - name: Check lint
      run: hatch fmt --check -py ${{ matrix.python-version }}
#      run : hatch run style:lint ${{ matrix.python-version }}

    - name: Run Test
      run : hatch test -py ${{ matrix.python-version }}

    - name: Run Coverage
      run : hatch test --cover -py ${{ matrix.python-version }}
